// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plantil.Data;

namespace Plantil.Data.Migrations
{
    [DbContext(typeof(PlantContext))]
    partial class PlantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Plantil.Domain.Entities.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExperimentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.GrowthRecommend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Recommend")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("GrowthRecommends");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Multiplication")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaxonomyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaxonomyId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.PlantExperiment", b =>
                {
                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.HasKey("PlantId", "ExperimentId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("PlantExperiment");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.Planter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.ToTable("Planters");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.Taxonomy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Taxonomys");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.Experiment", b =>
                {
                    b.HasOne("Plantil.Domain.Entities.Plant", null)
                        .WithMany("Experiments")
                        .HasForeignKey("PlantId");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.GrowthRecommend", b =>
                {
                    b.HasOne("Plantil.Domain.Entities.Plant", null)
                        .WithMany("GrowthRecommends")
                        .HasForeignKey("PlantId");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.Plant", b =>
                {
                    b.HasOne("Plantil.Domain.Entities.Taxonomy", "Taxonomy")
                        .WithMany()
                        .HasForeignKey("TaxonomyId");
                });

            modelBuilder.Entity("Plantil.Domain.Entities.PlantExperiment", b =>
                {
                    b.HasOne("Plantil.Domain.Entities.Experiment", "Experiment")
                        .WithMany("PlantExperiments")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantil.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantil.Domain.Entities.Planter", b =>
                {
                    b.HasOne("Plantil.Domain.Entities.Plant", null)
                        .WithOne("Planter")
                        .HasForeignKey("Plantil.Domain.Entities.Planter", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
